stages:
  - build
  - test
  - deploy

variables:
  KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: ddprof
  BASE_IMG: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/ddprof:base
  BUILD_IMG: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/ddprof:build
  S3_PREFIX: s3://binaries.ddbuild.io/ddprof/release
  RELPATH: ddprof/release

# This is the base repo (apt, system configuration, etc)
build:base:
  stage: build
  when: manual
  tags: ["runner:docker", "size:large"]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:18.03.1
  script:
  - set -euo pipefail
  - docker pull $BASE_IMG || true
  - docker build --tag $BASE_IMG app/base-env
  - docker push $BASE_IMG

# This is a cache of compile-time dependencies, like elfutils and libddprof.
# This needs to be updated whenever these dependencies change and it matters,
# but it may be more constructive to defer the libddprof pull until a more
build:deps:
  stage: build
  allow_failure: true
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  when: manual
  tags: ["runner:docker", "size:large"]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:18.03.1
  script:
  - set -euo pipefail
  - docker build --tag $BUILD_IMG -f app/build-env/Dockerfile .
  - docker push $BUILD_IMG

build:ddprof:
  image: $BUILD_IMG
  stage: build
  tags: ["runner:docker", "size:large"]
  variables:
    ANAME: ddprof
    BINPATH: release
    RELEASEBIN: $BINPATH/release/$ANAME
    DEBUGBIN: $BINPATH/debug/$ANAME
  artifacts:
    paths:
    - $RELEASEBIN
    - $DEBUGBIN
    expire_in: 1 day
  script:
  - set -euo pipefail
  - rm -rf vendor/elfutils
  - ln -s /app/vendor/elfutils vendor/elfutils
  - mkdir -p release/release
  - mkdir -p release/debug
  - make ANALYSIS=0 build
  - mv $BINPATH/$ANAME $DEBUGBIN
  - make DEBUG=0 ANALYSIS=0 SAFETY=0 build
  - cp $BINPATH/$ANAME $RELEASEBIN

deploy:ddprof:
  image: $BUILD_IMG
  stage: deploy
  tags: ["runner:docker", "size:large"]
  variables:
    ANAME: ddprof
    BINPATH: release
    RELEASEBIN: $BINPATH/release/$ANAME
    DEBUGBIN: $BINPATH/debug/$ANAME
  rules:
  - if: '$CI_COMMIT_BRANCH == "main"'
    when: always
  - if: '$CI_COMMIT_BRANCH != "main"'
    when: manual
  script:
  - set -euo pipefail
  - tools/ci_upload.sh

build:collatz:
  image: $BUILD_IMG
  stage: build
  tags: ["runner:docker", "size:large"]
  when: manual
  artifacts:
    paths:
    - $RELEASEBIN
    - $DEBUGBIN
    expire_in: 1 day
  variables:
    ANAME: collatz
    BINPATH: release
    RELEASEBIN: $BINPATH/release
    DEBUGBIN: $BINPATH/debug
  script:
  - set -euo pipefail
  - rm -rf vendor
  - ln -s /app/vendor vendor
  - make DEBUG=0 ANALYSIS=0 bench

deploy:collatz:
  image: $BUILD_IMG
  stage: deploy
  tags: ["runner:docker", "size:large"]
  when: manual
  variables:
    ANAME: collatz
    BINPATH: release
    RELEASEBIN: $BINPATH/release
    DEBUGBIN: $BINPATH/debug
  script:
  - set -euo pipefail
  - tools/ci_upload.sh
