stages:
  - build
  - test
  - deploy

variables:
  KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: ddprof
  # Cache of the valid images to start build steps faster : https://gitlab.ddbuild.io/DataDog/ddprof/-/jobs/78076731
  BUILD_IMG_STICKY: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/ddprof@sha256:f0c7bf2d2b8dd1dee28f0f0f35c550f3822ad1a63f8d48a8588e2952a5bb7d13
  # https://gitlab.ddbuild.io/DataDog/ddprof/-/jobs/78136292
  TEST_IMG_STICKY: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/ddprof@sha256:98d26ab6ca3f8f1e3ae770418e4ac732d153d3eabc4e20d58104b34bc3f9546a
  # When build images are built, publish them with following tags
  BASE_IMG: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/ddprof:base
  BUILD_IMG: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/ddprof:build
  TEST_IMG: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/ddprof:test
  # Deployment paths
  S3_PREFIX: s3://binaries.ddbuild.io/ddprof/release
  RELPATH: ddprof/release
  BINPATH: deliverables
  S3ROOT: ddprof

# This is the base repo (apt, system configuration, etc)
build:base:
  stage: build
  when: manual
  tags: ["runner:docker", "size:large"]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:18.03.1
  script:
    - set -euo pipefail
    - docker pull $BASE_IMG || true
    - docker build --tag $BASE_IMG app/base-env
    - docker push $BASE_IMG

# This is a cache of compile-time dependencies, like elfutils and libddprof.
# This needs to be updated whenever these dependencies change and it matters,
build:deps:
  stage: build
  allow_failure: true
  when: manual
  tags: ["runner:docker", "size:large"]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:18.03.1
  script:
    - set -euo pipefail
    - docker build --tag $BUILD_IMG --build-arg CI=${CI} -f app/build-env/Dockerfile .
    - docker push $BUILD_IMG

# This is a cache of compile-time dependencies, test image
build:testing:
  stage: build
  allow_failure: true
  when: manual
  tags: ["runner:docker", "size:large"]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:18.03.1
  script:
    - set -euo pipefail
    - docker build --tag $TEST_IMG --build-arg CI=${CI} -f app/test-env/Dockerfile .
    - docker push $TEST_IMG

.light-job-resource-allocation:
  variables:
    KUBERNETES_CPU_REQUEST: 2
    KUBERNETES_CPU_LIMIT: 2
    KUBERNETES_MEMORY_REQUEST: 4Gi
    KUBERNETES_MEMORY_LIMIT: 4Gi

# Migrating to a cmake build system. Both co-exist for now
build:ddprof_cmake:
  extends:
    - .light-job-resource-allocation
  image: $BUILD_IMG_STICKY
  stage: build
  tags: ["runner:k8s"]
  parallel:
    matrix:
      - BUILD_TYPE: ["Release", "Debug", "SanitizedDebug"]
  variables:
    BUILDPATH: build_${BUILD_TYPE}
  script:
    - set -euxo pipefail
    - export DELIVERY_PATH="${CI_PROJECT_DIR}/${BINPATH}/${BUILD_TYPE}"
    - mkdir -p vendor
    #Build image dependencies were stored in app, avoid rebuilding vendor content
    - ln -s /app/vendor/elfutils vendor/elfutils
    - ln -s /app/vendor/libddprof vendor/libddprof
    - ln -s /app/vendor/llvm vendor/llvm
    - mkdir -p ${BUILDPATH} && cd ${BUILDPATH}
    - cmake -DCMAKE_INSTALL_PREFIX=${DELIVERY_PATH} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DBUILD_REV=${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA} ..
    # Static checks
    - make cppcheck
    - make -j ${KUBERNETES_CPU_LIMIT}
    - if [ ! $(./ddprof --version | sed 's/.*+//g') == "${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}" ]; then exit 1; fi
    - ctest --repeat-until-fail 5 --output-on-failure | tee test-output.log
    - make install
      # This job gives useful info on the config of CI (perfopen allowed sizes)
    - cd test && ./mmap-ut
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/${BINPATH}/
    expire_in: 1 week

test:ddprof_cmake:
  extends:
    - .light-job-resource-allocation
  image: $TEST_IMG_STICKY
  stage: test
  tags: ["runner:k8s"]
  parallel:
    matrix:
      - BUILD_TYPE: ["Release", "SanitizedDebug"]
  script:
    - set -euxo pipefail
    - source setup_env.sh
    - echo "CHECK SETTING ON PERF EVENT PARANOID" && cat /proc/sys/kernel/perf_event_paranoid
    - echo "CHECK SETTING ON PINNED MEMORY" && ulimit -l
    - echo "CHECK SETTING on PERF EVEN OPEN" && cat /proc/sys/kernel/perf_event_mlock_kb
    - echo ""
    - echo "CHECK SETTING ON CPUs" && lscpu
    - echo ""
    - echo "CHECK SETTING ON EFFECTIVE CPUs" && find /sys/fs/cgroup/cpuset -type f -printf "%f\n" -exec cat {} \;
    - check_dependencies.sh ${BINPATH}/${BUILD_TYPE}/bin/ddprof test/data/expected_deps_${BUILD_TYPE}.txt
    # Run toy project for 5 seconds
    - run.sh -b ./${BINPATH}/${BUILD_TYPE}/bin BadBoggleSolver_run 5
  dependencies:
    - build:ddprof_cmake

.ddprof_job:
  variables:
    BINNAME: ddprof
    RELEASEBIN: ${BINPATH}/Release/bin/$BINNAME
    DEBUGBIN: ${BINPATH}/Debug/bin/$BINNAME
    GIT_SUBMODULE_STRATEGY: recursive
    PROMOTE: NONE
  image: $BUILD_IMG_STICKY

deploy:ddprof:
  extends: .ddprof_job
  when: always
  image: $BUILD_IMG_STICKY
  stage: deploy
  tags: ["runner:k8s"]
  script:
    - set -euo pipefail
    - if [ $CI_COMMIT_BRANCH = "main" ];then PROMOTE=MAJOR;fi
    - tools/ci_upload.sh
  dependencies:
    - build:ddprof_cmake

.collatz_job:
  variables:
    BINNAME: collatz
    RELEASEBIN: $BINPATH/release/$BINNAME
    DEBUGBIN: $BINPATH/debug/$BINNAME
    GIT_SUBMODULE_STRATEGY: recursive
    PROMOTE: NONE
  image: $BUILD_IMG_STICKY

build:collatz:
  extends: .collatz_job
  stage: build
  tags: ["runner:k8s"]
  artifacts:
    paths:
      - $RELEASEBIN
      - $DEBUGBIN
    expire_in: 1 day
  script:
    - set -euo pipefail
    - rm -rf vendor
    - ln -s /app/vendor vendor
    - mkdir -p $BINPATH/release
    - mkdir -p $BINPATH/debug
    - make ANALYSIS=0 bench
    - mv $BINPATH/$BINNAME $DEBUGBIN
    - make DEBUG=0 ANALYSIS=0 SAFETY=0 bench
    - mv $BINPATH/$BINNAME $RELEASEBIN

deploy:collatz:
  extends: .collatz_job
  image: $BUILD_IMG_STICKY
  stage: deploy
  tags: ["runner:k8s"]
  script:
    - set -euxo pipefail
    - if [ $CI_COMMIT_BRANCH = "main" ];then PROMOTE=MAJOR;fi
    - tools/ci_upload.sh
