stages:
  - build
  - test
  - deploy

variables:
  KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: ddprof
  # Cache of the valid images to start build steps faster
  BUILD_IMG_STICKY: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/ddprof@sha256:709d1a8560d8cdbe53768249f9782f39df6a0588a74c3e0d198aac8a5cfe17c5
  # When build images are built, publish them with following tags
  BASE_IMG: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/ddprof:base
  BUILD_IMG: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/ddprof:build
  # Deployment paths
  S3_PREFIX: s3://binaries.ddbuild.io/ddprof/release
  RELPATH: ddprof/release
  BINPATH: release
  S3ROOT: ddprof

# This is the base repo (apt, system configuration, etc)
build:base:
  stage: build
  when: manual
  tags: ["runner:docker", "size:large"]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:18.03.1
  script:
    - set -euo pipefail
    - docker pull $BASE_IMG || true
    - docker build --tag $BASE_IMG app/base-env
    - docker push $BASE_IMG

# This is a cache of compile-time dependencies, like elfutils and libddprof.
# This needs to be updated whenever these dependencies change and it matters,
build:deps:
  stage: build
  allow_failure: true
  when: manual
  tags: ["runner:docker", "size:large"]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:18.03.1
  script:
    - set -euo pipefail
    - docker build --tag $BUILD_IMG -f app/build-env/Dockerfile .
    - docker push $BUILD_IMG

.light-job-resource-allocation:
  variables:
    KUBERNETES_CPU_REQUEST: 2
    KUBERNETES_CPU_LIMIT: 2
    KUBERNETES_MEMORY_REQUEST: 4Gi
    KUBERNETES_MEMORY_LIMIT: 4Gi

# Migrating to a cmake build system. Both co-exist for now
build:ddprof_cmake:
  extends:
    - .light-job-resource-allocation
  image: $BUILD_IMG_STICKY
  stage: build
  tags: ["runner:docker", "size:large"]
  variables:
    TESTPATH: test
    BUILD_TYPE: Debug
    BUILDPATH: build_${BUILD_TYPE}
  script:
    - set -euxo pipefail
    - mkdir -p ${BUILDPATH} && cd ${BUILDPATH}
    - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ../
    - make -j ${KUBERNETES_CPU_LIMIT}
    - cd ${TESTPATH} && ctest --repeat-until-fail 5 --output-on-failure | tee test-output.log

.ddprof_job:
  variables:
    BINNAME: ddprof
    RELEASEBIN: $BINPATH/release/$BINNAME
    DEBUGBIN: $BINPATH/debug/$BINNAME
    GIT_SUBMODULE_STRATEGY: recursive
    PROMOTE: NONE
  image: $BUILD_IMG_STICKY

build:ddprof:
  extends: .ddprof_job
  stage: build
  tags: ["runner:docker", "size:large"]
  artifacts:
    paths:
      - $RELEASEBIN
      - $DEBUGBIN
    expire_in: 1 day
  script:
    - set -euo pipefail
    - rm -rf vendor/elfutils
    - ln -s /app/vendor/elfutils vendor/elfutils
    - ls -l vendor
    - ls -l vendor/libddprof
    - mkdir -p release/release
    - mkdir -p release/debug
    - make ANALYSIS=0 build
    - mv $BINPATH/$BINNAME $DEBUGBIN
    - make DEBUG=0 ANALYSIS=0 SAFETY=0 build
    - cp $BINPATH/$BINNAME $RELEASEBIN

deploy:ddprof:
  extends: .ddprof_job
  when: always
  image: $BUILD_IMG_STICKY
  stage: deploy
  tags: ["runner:docker", "size:large"]
  script:
    - set -euo pipefail
    - if [ $CI_COMMIT_BRANCH = "main" ];then PROMOTE=MAJOR;fi
    - tools/ci_upload.sh

.collatz_job:
  variables:
    BINNAME: collatz
    RELEASEBIN: $BINPATH/release/$BINNAME
    DEBUGBIN: $BINPATH/debug/$BINNAME
    GIT_SUBMODULE_STRATEGY: recursive
    PROMOTE: NONE
  image: $BUILD_IMG_STICKY

build:collatz:
  extends: .collatz_job
  stage: build
  tags: ["runner:docker", "size:large"]
  artifacts:
    paths:
      - $RELEASEBIN
      - $DEBUGBIN
    expire_in: 1 day
  script:
    - set -euo pipefail
    - rm -rf vendor
    - ln -s /app/vendor vendor
    - mkdir -p release/release
    - mkdir -p release/debug
    - make ANALYSIS=0 bench
    - mv $BINPATH/$BINNAME $DEBUGBIN
    - make DEBUG=0 ANALYSIS=0 SAFETY=0 bench
    - mv $BINPATH/$BINNAME $RELEASEBIN

deploy:collatz:
  extends: .collatz_job
  image: $BUILD_IMG_STICKY
  stage: deploy
  tags: ["runner:docker", "size:large"]
  script:
    - set -euxo pipefail
    - if [ $CI_COMMIT_BRANCH = "main" ];then PROMOTE=MAJOR;fi
    - tools/ci_upload.sh
